pipeline:
  name: citriggerpipe
  identifier: citriggerpipe
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    trigger: ""
    CIremote: ""
  properties:
    ci:
      codebase:
        connectorRef: account.tempgitcon
        build: <+input>
  stages:
    - stage:
        name: cistage
        identifier: cistage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8con
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: nwdockerconnector
                    image: nginx
                    shell: Sh
                    command: echo "hii"
