pipeline:
  name: fielpipeline
  identifier: fielpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        tags: {}
        template:
          templateRef: filegit
          versionLabel: "1.0"
          templateInputs:
            spec:
              service:
                serviceInputs: <+input>
