pipeline:
  name: tagpp
  identifier: tagpp
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    test_tag: "123"
    project_id: <+pipeline.variables.id>
    test_tag1: "1234"
    new_tag1: "0987"
  stages:
    - stage:
        name: dep
        identifier: dep
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Dummyservice
          environment:
            environmentRef: en1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infradk
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hii"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
